name:
  publish to ecr

  # Trigger the workflow on push or pull request,
  # but only for the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to ecr
    runs-on: ubuntu-latest
    steps:
      - run: docker build --tag ${GITHUB_REPOSITORY}:${GITHUB_SHA} ..
      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          local-image: ${ { GITHUB_REPOSITORY }:{ GITHUB_SHA } }
          image: a, ${ { GITHUB_REPOSITORY }:latest }
